FROM node:22-alpine

WORKDIR /backend

COPY package*.json ./

RUN npm i

EXPOSE 5000

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:5000/ || exit 1

CMD [ "npm","run","dev" ]
